### ISSUE TITLE
Components r, g, b and a are not translated correctly

### ISSUE THREAD

**Issue by b005t3r** [Barliesque/EasyAGAL#6]
When I use rgba component they are somehow omitted in the actual uploaded shader (checked using Adobe Scout). My "fix" for this is to return components with xyzw instead of rgba when using IRegister corresponding properties.

**Comment by Barliesque** [comment]
I remember encountering this problem when I first created the library.  The
problem was actually in AGALMiniAssembler itself.  I bet that problem has
crept back in since they made their updates to AGAL3.  I'll see if I can
track it down.

**Comment by b005t3r** [comment]
Thanks for the reply, David!

I guess is has something to do with mixing both rgba and xyzw in the shader's code. My working workaround/fix is to internally use xyzw instead of rgba for the rgba Components, like so:

Register.as
```as3
		public function get x():Component { return new Component(this, "x"); }
		public function get y():Component { return new Component(this, "y"); }
		public function get z():Component { return new Component(this, "z"); }
		public function get w():Component { return new Component(this, "w"); }
		
		public function get r():Component { return new Component(this, "x"); }
		public function get g():Component { return new Component(this, "y"); }
		public function get b():Component { return new Component(this, "z"); }
		public function get a():Component { return new Component(this, "w"); }
		
		public function get xy():ComponentSelection { return new ComponentSelection(this, "xy"); }
		public function get zw():ComponentSelection { return new ComponentSelection(this, "zw"); }
		
		public function get xyz():ComponentSelection { return new ComponentSelection(this, "xyz"); }
		public function get rgb():ComponentSelection { return new ComponentSelection(this, "xyz"); }
``` 

Component.as

```as3
		/// @private
		static public function valid(prop:String):Boolean {
			switch(prop) {
				case "x":	case "y":	case "z":	case "w":
				//case "r":	case "g":	case "b":	case "a":
					return true;
			}
			return false;
		}
```

**Comment by b005t3r** [comment]
Also, I saw @henke37 created a non-static version of EasyAGAL. It would be great if you could merge his pull request too.

**Comment by Barliesque** [comment]
Okay, I've committed a new version of AGALMiniAssembler.as   ...As I suspected, Adobe have accidentally stomped the fix for RGBA components, so I've reapplied that fix to the latest version.  Please let me know if this works or doesn't -- my time is very limited at the moment, so I haven't done as much testing as I'd like!
...next, I'll add the new opcodes and increased limits.

**Comment by b005t3r** [comment]
Sure, I can give it a try tomorrow - I have an example app which breaks instantly with mixed components.

**Comment by b005t3r** [comment]
Just tested your change and there still is a bug with mixing xyzw and rgba components in one fragment shader, but now the resulting program doesn't work and throws an error (previously it run, but there were rendering errors - rgba components where simply removed from the code). I applied my workaround and it works.

I think using the workaround is the best option currently.
